### ISSUE TITLE
Can't Install for OXS Based Project

### ISSUE THREAD

**Issue by aventurella** [danparsons/DPHue#2]
[!] The platform of the target `Pods` (OS X 10.8) is not compatible with `DPHue (0.0.1)` which has a minimum requirement of iOS 5.0.

Looks like the spec file sets the Deployment target to iOS
s.ios.deployment_target = '5.0'

**Comment by jhurliman** [comment]
Same issue here. Should just be a podspec change?

**Comment by jhurliman** [comment]
This ticket can be closed.
